f = open("write_file.txt", "w")
f.write("I like Python's syntax")
f = open("write_file.txt", "a")
f.write("\nAfter this course I want to learn advance topic about Python")
f.write("\nI will apply the knowledge by practicing more")
f.write("\nOne of my goals is to become a Python developer")
f = open("write_file.txt", "r")
print(f.read())
f.close()